name: stip
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Flutter External Libraries
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.3
  fluttertoast: 
  share: 
  webview_flutter: 
  google_fonts:
  connectivity_plus:
  loading_animation_widget: 
  fullscreen:

  ## State Management
  provider: ^6.0.3

  ## Local Memory Storage
  shared_preferences: ^2.0.15
  adaptive_theme: ^3.0.0   

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_launcher_icons_maker: "^0.10.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/stip_logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/stip_logo.png
    - assets/images/stip_logo_with_text.png
    - assets/images/stip_mobile_splash_image_01.jpg
    - assets/images/stip_mobile_splash_image_02.jpeg
    - assets/images/stip_mobile_splash_ref.jpg
    - assets/images/mobile_splash_page.jpg
    - assets/images/tablet_splash_page.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
